-- Async online battles (Supabase-authenticated users).
-- Adds public opponent discovery, server-authoritative star balance, and match resolution RPC.

create table if not exists public.user_profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  display_name text not null check (char_length(trim(display_name)) between 1 and 40),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists user_profiles_display_name_idx on public.user_profiles (lower(display_name));

alter table public.user_profiles enable row level security;

create policy "user_profiles_select_all_auth"
  on public.user_profiles for select
  to authenticated
  using (true);

create policy "user_profiles_insert_self"
  on public.user_profiles for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "user_profiles_update_self"
  on public.user_profiles for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create table if not exists public.user_stars (
  user_id uuid primary key references auth.users (id) on delete cascade,
  stars integer not null default 0 check (stars >= 0),
  updated_at timestamptz not null default now()
);

alter table public.user_stars enable row level security;

create policy "user_stars_select_self"
  on public.user_stars for select
  to authenticated
  using (auth.uid() = user_id);

create policy "user_stars_insert_self"
  on public.user_stars for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "user_stars_update_self"
  on public.user_stars for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create table if not exists public.battle_matches (
  id uuid primary key default gen_random_uuid(),
  status text not null default 'pending' check (status in ('pending', 'resolved', 'cancelled')),
  challenger_user_id uuid not null references auth.users (id) on delete cascade,
  opponent_user_id uuid not null references auth.users (id) on delete cascade,
  star_wager integer not null check (star_wager >= 1),
  challenger_moves_hash text not null,
  challenger_moves_salt text,
  challenger_reveal_moves text[],
  opponent_moves text[],
  winner_user_id uuid references auth.users (id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint battle_matches_players_different check (challenger_user_id <> opponent_user_id),
  constraint battle_matches_challenger_reveal_three
    check (challenger_reveal_moves is null or array_length(challenger_reveal_moves, 1) = 3),
  constraint battle_matches_opponent_moves_three
    check (opponent_moves is null or array_length(opponent_moves, 1) = 3)
);

create index if not exists battle_matches_inbox_idx
  on public.battle_matches (opponent_user_id, status, created_at desc);
create index if not exists battle_matches_outbox_idx
  on public.battle_matches (challenger_user_id, status, created_at desc);

alter table public.battle_matches enable row level security;

create policy "battle_matches_select_participants"
  on public.battle_matches for select
  to authenticated
  using (auth.uid() = challenger_user_id or auth.uid() = opponent_user_id);

create policy "battle_matches_insert_challenger"
  on public.battle_matches for insert
  to authenticated
  with check (
    auth.uid() = challenger_user_id
    and status = 'pending'
    and opponent_moves is null
    and challenger_reveal_moves is null
    and winner_user_id is null
    and resolved_at is null
  );

create table if not exists public.battle_events (
  id bigint generated by default as identity primary key,
  match_id uuid not null references public.battle_matches (id) on delete cascade,
  event_type text not null,
  actor_user_id uuid references auth.users (id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists battle_events_match_idx
  on public.battle_events (match_id, created_at desc);

alter table public.battle_events enable row level security;

create policy "battle_events_select_participants"
  on public.battle_events for select
  to authenticated
  using (
    exists (
      select 1
      from public.battle_matches m
      where m.id = battle_events.match_id
        and (auth.uid() = m.challenger_user_id or auth.uid() = m.opponent_user_id)
    )
  );

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_touch_user_profiles on public.user_profiles;
create trigger trg_touch_user_profiles
before update on public.user_profiles
for each row execute procedure public.touch_updated_at();

drop trigger if exists trg_touch_user_stars on public.user_stars;
create trigger trg_touch_user_stars
before update on public.user_stars
for each row execute procedure public.touch_updated_at();

drop trigger if exists trg_touch_battle_matches on public.battle_matches;
create trigger trg_touch_battle_matches
before update on public.battle_matches
for each row execute procedure public.touch_updated_at();

create or replace function public.log_battle_match_created()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.battle_events (match_id, event_type, actor_user_id, payload)
  values (
    new.id,
    'challenge_created',
    new.challenger_user_id,
    jsonb_build_object('starWager', new.star_wager)
  );
  return new;
end;
$$;

drop trigger if exists trg_log_battle_match_created on public.battle_matches;
create trigger trg_log_battle_match_created
after insert on public.battle_matches
for each row execute procedure public.log_battle_match_created();

create or replace function public.ensure_user_profile(p_display_name text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'Not authenticated';
  end if;

  if p_display_name is null or char_length(trim(p_display_name)) = 0 then
    raise exception 'Display name required';
  end if;

  insert into public.user_profiles (user_id, display_name)
  values (v_uid, left(trim(p_display_name), 40))
  on conflict (user_id) do update
    set display_name = excluded.display_name,
        updated_at = now();

  insert into public.user_stars (user_id, stars)
  values (v_uid, 0)
  on conflict (user_id) do nothing;
end;
$$;

create or replace function public.resolve_battle_match(
  p_match_id uuid,
  p_challenger_moves text[],
  p_challenger_salt text
)
returns public.battle_matches
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_match public.battle_matches%rowtype;
  v_idx integer;
  v_p1_wins integer := 0;
  v_p2_wins integer := 0;
  v_p1_move text;
  v_p2_move text;
  v_xp1 integer := 0;
  v_xp2 integer := 0;
  v_transfer integer;
  v_challenger_stars integer;
  v_opponent_stars integer;
  v_hash text;
begin
  if v_uid is null then
    raise exception 'Not authenticated';
  end if;

  if p_challenger_moves is null or array_length(p_challenger_moves, 1) <> 3 then
    raise exception 'Challenger must reveal exactly 3 moves';
  end if;

  select *
  into v_match
  from public.battle_matches
  where id = p_match_id
  for update;

  if not found then
    raise exception 'Match not found';
  end if;

  if v_match.status <> 'pending' then
    raise exception 'Match already resolved or cancelled';
  end if;

  if v_uid <> v_match.challenger_user_id then
    raise exception 'Only challenger can resolve this match';
  end if;

  if v_match.opponent_moves is null or array_length(v_match.opponent_moves, 1) <> 3 then
    raise exception 'Opponent has not submitted moves';
  end if;

  v_hash := encode(digest(array_to_string(p_challenger_moves, ',') || ':' || coalesce(p_challenger_salt, ''), 'sha256'), 'hex');
  if v_hash <> v_match.challenger_moves_hash then
    raise exception 'Reveal does not match committed moves';
  end if;

  for v_idx in 1..3 loop
    v_p1_move := lower(trim(coalesce(p_challenger_moves[v_idx], '')));
    v_p2_move := lower(trim(coalesce(v_match.opponent_moves[v_idx], '')));

    if v_p1_move not in ('rock', 'paper', 'scissors') or v_p2_move not in ('rock', 'paper', 'scissors') then
      raise exception 'Invalid move in round %', v_idx;
    end if;

    if v_p1_move = v_p2_move then
      continue;
    elsif (v_p1_move = 'rock' and v_p2_move = 'scissors')
      or (v_p1_move = 'paper' and v_p2_move = 'rock')
      or (v_p1_move = 'scissors' and v_p2_move = 'paper') then
      v_p1_wins := v_p1_wins + 1;
    else
      v_p2_wins := v_p2_wins + 1;
    end if;
  end loop;

  if v_p1_wins = v_p2_wins then
    select coalesce(xp, 0) into v_xp1 from public.user_xp where user_id = v_match.challenger_user_id;
    select coalesce(xp, 0) into v_xp2 from public.user_xp where user_id = v_match.opponent_user_id;

    if v_xp1 > v_xp2 then
      v_p1_wins := v_p1_wins + 1;
    elsif v_xp2 > v_xp1 then
      v_p2_wins := v_p2_wins + 1;
    end if;
  end if;

  insert into public.user_stars (user_id, stars)
  values (v_match.challenger_user_id, 0)
  on conflict (user_id) do nothing;
  insert into public.user_stars (user_id, stars)
  values (v_match.opponent_user_id, 0)
  on conflict (user_id) do nothing;

  select stars into v_challenger_stars from public.user_stars where user_id = v_match.challenger_user_id for update;
  select stars into v_opponent_stars from public.user_stars where user_id = v_match.opponent_user_id for update;

  v_transfer := least(v_match.star_wager, v_challenger_stars, v_opponent_stars);

  if v_p1_wins > v_p2_wins and v_transfer > 0 then
    update public.user_stars set stars = stars + v_transfer where user_id = v_match.challenger_user_id;
    update public.user_stars set stars = stars - v_transfer where user_id = v_match.opponent_user_id;
    v_match.winner_user_id := v_match.challenger_user_id;
  elsif v_p2_wins > v_p1_wins and v_transfer > 0 then
    update public.user_stars set stars = stars - v_transfer where user_id = v_match.challenger_user_id;
    update public.user_stars set stars = stars + v_transfer where user_id = v_match.opponent_user_id;
    v_match.winner_user_id := v_match.opponent_user_id;
  else
    v_match.winner_user_id := null;
  end if;

  update public.battle_matches
  set status = 'resolved',
      winner_user_id = v_match.winner_user_id,
      challenger_reveal_moves = p_challenger_moves,
      challenger_moves_salt = p_challenger_salt,
      resolved_at = now(),
      updated_at = now()
  where id = v_match.id
  returning * into v_match;

  insert into public.battle_events (match_id, event_type, actor_user_id, payload)
  values (
    v_match.id,
    'resolved',
    v_uid,
    jsonb_build_object(
      'p1Wins', v_p1_wins,
      'p2Wins', v_p2_wins,
      'starsTransferred', v_transfer,
      'winnerUserId', v_match.winner_user_id
    )
  );

  return v_match;
end;
$$;

create or replace function public.submit_battle_opponent_moves(
  p_match_id uuid,
  p_moves text[]
)
returns public.battle_matches
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_match public.battle_matches%rowtype;
  v_idx integer;
  v_move text;
begin
  if v_uid is null then
    raise exception 'Not authenticated';
  end if;

  if p_moves is null or array_length(p_moves, 1) <> 3 then
    raise exception 'Opponent must submit exactly 3 moves';
  end if;

  for v_idx in 1..3 loop
    v_move := lower(trim(coalesce(p_moves[v_idx], '')));
    if v_move not in ('rock', 'paper', 'scissors') then
      raise exception 'Invalid move in round %', v_idx;
    end if;
  end loop;

  select *
  into v_match
  from public.battle_matches
  where id = p_match_id
  for update;

  if not found then
    raise exception 'Match not found';
  end if;

  if v_match.status <> 'pending' then
    raise exception 'Match already resolved or cancelled';
  end if;

  if v_uid <> v_match.opponent_user_id then
    raise exception 'Only opponent can submit moves';
  end if;

  if v_match.opponent_moves is not null then
    raise exception 'Opponent moves already submitted';
  end if;

  update public.battle_matches
  set opponent_moves = p_moves,
      updated_at = now()
  where id = p_match_id
  returning * into v_match;

  insert into public.battle_events (match_id, event_type, actor_user_id, payload)
  values (
    p_match_id,
    'opponent_submitted',
    v_uid,
    jsonb_build_object('movesSubmitted', true)
  );

  return v_match;
end;
$$;
